<?php

?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Last 5 Vehicles') ?></h4></div>
    <fieldset class="np"><?php echo $this->getChildHtml('lastVehicles'); ?></fieldset>
</div>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Top 5 Vehicles') ?></h4></div>
    <fieldset class="np"><?php echo $this->getChildHtml('topVehicles'); ?></fieldset>
</div>